#!/bin/bash
read -p "Hello and welcome to the class, please enter your name: " name
echo -e '\n'
echo This script has four different sections:
echo Section 1: Age Calculation
echo Section 2: Trivia Question
echo Section 3: Mathematical Operations:  Addition, Subtraction, Multiplication and Division
echo Section 4: Find your IP address..
echo -e '\n'
echo Section 1:  
echo "We will determine which drink you're allowed to have based on your age"
read -p "Please enter your age: " age
if [[ $age -le 0 ]]; then
        echo Invalid response
	elif [[ $age -lt 21 ]]; then
	        echo You are not an adult, you can ONLY have water or soda...
		elif [[ $age -ge 21 && $age -lt 100 ]]; then
		        echo You are an adult, feel free to grab a beer, it is hot outside!
			else
			        echo A valid 2 digit number was not entered
				fi
				echo -e '\n'
				echo Section 2:  
				read -p "Trivia question - What is the next number in the series; 1, 4, 9, 16, 25, …? " question
				test $question -eq 36  && echo Your answer is correct! || echo Your answer is incorrect, try again later...
				echo -e '\n'
				echo Section 3:
				read -p "Please enter a number: " number
				read -p "Please enter another number: " secnumber
				let sum_var="$number + $secnumber" ; echo "The result is $sum_var"
				let sub_var="$number - $secnumber" ; echo "The result is $sub_var"
				let mul_var="$number *  $secnumber" ; echo "The result is $mul_var"
				let div_var="$number / $secnumber" ; echo "The result is $div_var"
				echo -e '\n'
				echo Section 4:
				read -p "Would you like to display your hostname: " prompt
				if  [[ "$prompt" == y || "$prompt" == Y || "$prompt" == yes || "$prompt" == Yes ]]; then
				echo Here is your hostname=$(hostname)  
				else
				echo Your hostname will not be displayed.
				fi
				echo "Thanks for being part of this script!"
